/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo76.Vistas;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import universidadgrupo76.AccesoADatos.AlumnoData;
import universidadgrupo76.entidades.Alumno;

/**
 *
 * @author Mati_ssd
 */
public class IJAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IJAlumnos
     */
    public IJAlumnos() {
        initComponents();
        agregarListenerJtcodigo();
        bloquearBoton();
    }
    int idalumno = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtdocumento = new javax.swing.JTextField();
        jtapellido = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        jrActivo = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jbbuscar = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alumno");

        jSeparator1.setForeground(new java.awt.Color(129, 233, 192));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Documento :");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellido :");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado : ");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre : ");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de Nacimiento :");

        jtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdocumentoActionPerformed(evt);
            }
        });

        jrActivo.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jrActivo.setText("Activo");
        jrActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActivoActionPerformed(evt);
            }
        });

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jbbuscar.setBackground(new java.awt.Color(129, 233, 192));
        jbbuscar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbbuscar.setText("Buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jbnuevo.setBackground(new java.awt.Color(129, 233, 192));
        jbnuevo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbnuevo.setText("Nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbeliminar.setBackground(new java.awt.Color(129, 233, 192));
        jbeliminar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbguardar.setBackground(new java.awt.Color(129, 233, 192));
        jbguardar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbguardar.setText("Guardar");

        jbsalir.setBackground(new java.awt.Color(247, 166, 166));
        jbsalir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jbguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel1)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbbuscar)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrActivo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdocumentoActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed

        boolean estado = false;
        int documento = 0;
        String apellido = "";
        String nombre = "";

        try {
            documento = Integer.parseInt(jtdocumento.getText());
            if (jtapellido.getText().isEmpty() || jtnombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No pueden quedar campos vacios");
                return;
            }
            apellido = jtapellido.getText();
            nombre = jtnombre.getText();

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Deve ingresar solo nsumero enteros");

        }

        if (jDateChooser1.getDate() != null) {
            LocalDate fechaN = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            // DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            if (jrActivo.isSelected()) {
                estado = true;
            }

            Alumno nuevo = new Alumno(documento, nombre, apellido, fechaN, estado);

            AlumnoData alu = new AlumnoData();

            try {
                alu.guardarAlumno(nuevo);
                jtdocumento.setText("");
                jtapellido.setText("");
                jtnombre.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(IJAlumnos.class.getName()).log(Level.SEVERE, null, ex);

            }
        }


    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jrActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActivoActionPerformed

    }//GEN-LAST:event_jrActivoActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        try {
            AlumnoData alu = new AlumnoData();
            int dni = Integer.parseInt(jtdocumento.getText());

            Alumno alumnoEncontrado = alu.buscarAlumnoPordni(dni);

            if (alumnoEncontrado != null) {
                idalumno = alumnoEncontrado.getIdAlumno();
                jtapellido.setText(alumnoEncontrado.getApellido());
                jtnombre.setText(alumnoEncontrado.getNombre());
                jrActivo.setSelected(true);
                jDateChooser1.setDate(java.sql.Date.valueOf(alumnoEncontrado.getFechaNacimiento()));
                JOptionPane.showMessageDialog(null, "Alumno encontrado.");
            } else {
                JOptionPane.showMessageDialog(null, "Alumno no encontrado.");
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Debe ingresar solo números enteros");
        }

    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if (idalumno > 0) {
            AlumnoData alu = new AlumnoData();
            alu.eliminarAlumno(idalumno);
            JOptionPane.showMessageDialog(null, "Alumno eliminado exitosamente.");
            jtdocumento.setText("");
            jtapellido.setText("");
            jtnombre.setText("");
             jDateChooser1.setDate(null);
            jrActivo.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un alumno válido para eliminar.");
        }
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JRadioButton jrActivo;
    private javax.swing.JTextField jtapellido;
    private javax.swing.JTextField jtdocumento;
    private javax.swing.JTextField jtnombre;
    // End of variables declaration//GEN-END:variables
private boolean contieneSoloLetras(String texto) {
        return texto.matches("[a-zA-Z]+");
    }
private void agregarListenerJtcodigo() {
    jtdocumento.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            bloquearBoton(); // Llama al método que verifica y ajusta el estado del botón
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            bloquearBoton(); // Llama al método que verifica y ajusta el estado del botón
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Este método se utiliza para campos que no son de texto, como JComboBox, no es relevante aquí.
        }
    });
}


private void bloquearBoton(){
    if (!jtdocumento.getText().isEmpty()) {
        jbeliminar.setEnabled(true);
        jbbuscar.setEnabled(true);
        jbnuevo.setEnabled(true);
        jbguardar.setEnabled(true);
    }else{
    jbeliminar.setEnabled(false);
        jbbuscar.setEnabled(false);
        jbnuevo.setEnabled(false);
        jbguardar.setEnabled(false);
    }
        
    
}

}
