/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo76.Vistas;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import universidadgrupo76.AccesoADatos.MateriaData;
import universidadgrupo76.entidades.Materia;

/**
 *
 * @author Mati_ssd
 */
public class IJMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form IJMateria
     */
    public IJMateria() {
        initComponents();
        inicializar();
    }
    MateriaData mata = new MateriaData();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbbuscar = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();
        jractivo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtcodigo = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        jtaño = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel3.setText("Año:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel4.setText("Estado:");

        jbbuscar.setBackground(new java.awt.Color(129, 233, 192));
        jbbuscar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbbuscar.setText("Buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jbnuevo.setBackground(new java.awt.Color(129, 233, 192));
        jbnuevo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbnuevo.setText("Nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbeliminar.setBackground(new java.awt.Color(129, 233, 192));
        jbeliminar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbguardar.setBackground(new java.awt.Color(129, 233, 192));
        jbguardar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbsalir.setBackground(new java.awt.Color(247, 166, 166));
        jbsalir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        jractivo.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jractivo.setText("Activo");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Materia");

        jSeparator1.setForeground(new java.awt.Color(129, 233, 192));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jbguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jractivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jtaño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jractivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
        // TODO add your handling code here:
        try{
        if (!jtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo codigo tiene que estar vacio");
            jtcodigo.setText("");
        }
        String nombre = jtnombre.getText();
        int año = Integer.parseInt(jtaño.getText());
        boolean estado = jractivo.isSelected();
        Materia nuevaMateria = new Materia(nombre, año, estado);
        mata.guardarMateria(nuevaMateria);
        jtnombre.setText("");
        jtaño.setText("");
        jractivo.setSelected(false);
        }catch (NumberFormatException  e){
                    JOptionPane.showMessageDialog(null, "Por favor, ingresa un año válido.");

        }
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        if (jtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo codigo no tiene que estar vacio");
            return;
        }
        try{
        int codigo=Integer.parseInt(jtcodigo.getText());
       Materia materiaEncontrada=mata.buscarMateria(codigo);
       if(materiaEncontrada!=null){
           JOptionPane.showMessageDialog(null, "Materia encontrada");
        jtnombre.setText(materiaEncontrada.getNombre());
        jtaño.setText(materiaEncontrada.getAno()+"");
        jractivo.setSelected(materiaEncontrada.isEstado());
    }
       } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo código debe ser un número válido");
    }//GEN-LAST:event_jbbuscarActionPerformed
    }
    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
        try{
        int codigo=Integer.parseInt(jtcodigo.getText());
        if (!jtcodigo.getText().isEmpty()) {
            mata.EliminadoLogiMateria(codigo);
            JOptionPane.showMessageDialog(null, "Materia Eliminada con exito");
            jtcodigo.setText("");
           jtnombre.setText("");
        jtaño.setText("");
        jractivo.setSelected(false); 
        }else{
                    JOptionPane.showMessageDialog(null, "No se puede eliminar la materia");

        }
         } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo código debe ser un número válido");
    }        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        // TODO add your handling code here:
        int codigo=Integer.parseInt(jtcodigo.getText());
        String nombre=jtnombre.getText();
        int año=Integer.parseInt(jtaño.getText());
        boolean estado=jractivo.isSelected();
        Materia modificado=new Materia(codigo,nombre,año,estado);
        mata.modificarmateria(modificado);
        jtcodigo.setText("");
           jtnombre.setText("");
        jtaño.setText("");
        jractivo.setSelected(false); 
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jbsalirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JRadioButton jractivo;
    private javax.swing.JTextField jtaño;
    private javax.swing.JTextField jtcodigo;
    private javax.swing.JTextField jtnombre;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
    bloquearBoton(); 
    agregarListenerJtcodigo(); 
}

private void agregarListenerJtcodigo() {
    // Agregamos un DocumentListener al campo jtnombre
    jtnombre.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            bloquearBoton();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            bloquearBoton();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // No es relevante aquí
        }
    });
    
    // Agregamos un DocumentListener al campo jtcodigo
    jtcodigo.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            bloquearBoton();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            bloquearBoton();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // No es relevante aquí
        }
    });
}

private void bloquearBoton() {
    // Verificamos si alguno de los campos (jtcodigo o jtnombre) está vacío
    if (jtcodigo.getText().isEmpty() && jtnombre.getText().isEmpty()) {
        habilitarBotones(false); // Si ambos están vacíos, deshabilitamos los botones
    } else {
        habilitarBotones(true); // Si alguno de los dos tiene contenido, habilitamos los botones
    }
}

private void habilitarBotones(boolean habilitar) {
    jbeliminar.setEnabled(habilitar);
    jbbuscar.setEnabled(habilitar);
    jbnuevo.setEnabled(habilitar);
    jbguardar.setEnabled(habilitar);
}
}
