/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo76.Vistas;

import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import universidadgrupo76.AccesoADatos.AlumnoData;
import universidadgrupo76.AccesoADatos.InscripcionData;
import universidadgrupo76.AccesoADatos.MateriaData;
import universidadgrupo76.entidades.Alumno;
import universidadgrupo76.entidades.Materia;

/**
 *
 * @author Mati_ssd
 */
public class JFFManipulacionDeNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFFManipulacionDeNotas
     */
    
    AlumnoData ad = new AlumnoData();
    MateriaData md = new MateriaData();
    InscripcionData id = new InscripcionData();
     int idTabla=0;
     int editarNota=0;
      int idmateria1=0;
     private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false; 
        }
    };
     
    public JFFManipulacionDeNotas() {
        initComponents();
        CargarComboBox();
        armarCabecera();
        tablaConMateriaInscripta();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jbmodificar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Carga de Notas");

        jSeparator1.setForeground(new java.awt.Color(129, 233, 192));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel2.setText("Seleccione un Alumno :");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jbmodificar.setBackground(new java.awt.Color(129, 233, 192));
        jbmodificar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbmodificar.setText("Modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jbsalir.setBackground(new java.awt.Color(247, 166, 166));
        jbsalir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jbmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
          Alumno alumnoSeleccionado = (Alumno) jComboBox1.getSelectedItem();
        idTabla = alumnoSeleccionado.getIdAlumno();
     tablaConMateriaInscripta();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
       // Obtener la fila seleccionada
    int filaSeleccionada = jTable.getSelectedRow();

    if (filaSeleccionada == -1) {
        // Si no se seleccionó ninguna fila, mostrar un mensaje de advertencia
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila de la tabla para modificar.");
    } else {
        // Obtener el ID de materia de la fila seleccionada
        int idMateria = (int) jTable.getValueAt(filaSeleccionada, 0);

        // Solicitar al usuario que ingrese la nueva nota
        String notaStr = JOptionPane.showInputDialog(null, "Ingrese la nueva nota:");

        try {
            // Convertir la entrada del usuario a un entero
            int nuevaNota = Integer.parseInt(notaStr);

            // Actualizar la base de datos con la nueva nota
            id.modificarNota(idTabla, idMateria, nuevaNota);

            // Actualizar la tabla con la nueva nota
            jTable.setValueAt(nuevaNota, filaSeleccionada, 2);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Nota modificada con éxito.");
        } catch (NumberFormatException e) {
            // Si el usuario ingresa algo que no se puede convertir a un número, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor numérico válido.");
        }
    }
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int filaSeleccionada = jTable.getSelectedRow();
    if (filaSeleccionada != -1) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        editarNota = (int) model.getValueAt(filaSeleccionada, 2);
    }
        
    }//GEN-LAST:event_jTableMouseClicked

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
          this.dispose();
    }//GEN-LAST:event_jbsalirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbsalir;
    // End of variables declaration//GEN-END:variables

 private void CargarComboBox() {
        for (Alumno alumno : id.obtenerAlumnosXMateria1()){
            jComboBox1.addItem(alumno);
        }
    }

private void armarCabecera() {
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("NOTA");
        jTable.setModel(modelo);
    }
private void tablaConMateriaInscripta() {
        modelo.setRowCount(0);
        for (Materia inscripciones : id.obtenernotaCursadas(idTabla)) {
            modelo.addRow(new Object[]{inscripciones.getIdMateria(), inscripciones.getNombre(), inscripciones.getAno()});
            idmateria1=inscripciones.getIdMateria();
        }

    }
private void escuchar(){
jTable.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                int fila = e.getFirstRow();
                int columna = e.getColumn();
                if (columna == 2) { // Columna de notas
                    DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                    editarNota = (int) model.getValueAt(fila, columna);
                    // Actualizar la base de datos con la nueva nota
                   // id.modificarNota(idTabla, idmateria1, nuevaNota);
                }
            }
        });
}

}