/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo76.Vistas;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Mati_ssd
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Escritorio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sin título.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));

        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jMenuItem3.setText("Formulario de Alumno");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jMenuItem4.setText("Formularios de Materia");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Administración");

        jMenuItem5.setText("Manejo de Inscripciones");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem8.setText("Manipulacion de notas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultas");

        jMenuItem9.setText("Alumnos Por Materia");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Crear una instancia de IJAlumnos
        IJAlumnos ija = new IJAlumnos();

        // Establecer el tamaño deseado para la ventana
        int ancho = 600;
        int alto = 400;
        ija.setSize(ancho, alto);

        // Obtener las dimensiones del escritorio
        Dimension desktopSize = Escritorio.getSize();

        // Obtener las dimensiones de la ventana interna
        Dimension frameSize = ija.getSize();

        // Calcular las coordenadas X e Y para centrar la ventana en el escritorio
        int xPos = (desktopSize.width - frameSize.width) / 2;
        int yPos = (desktopSize.height - frameSize.height) / 2;

        // Establecer la posición en el centro del escritorio
        ija.setLocation(xPos, yPos);

        // Hacer la ventana interna visible
        ija.setVisible(true);

        // Agregar la ventana interna al escritorio
        Escritorio.add(ija);

        // Colocar la ventana interna al frente
        Escritorio.moveToFront(ija);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        // Crear una instancia de IJAlumnos
        IJMateria ijm = new IJMateria();

        // Establecer el tamaño deseado para la ventana
        int ancho = 600;
        int alto = 400;
        ijm.setSize(ancho, alto);

        // Obtener las dimensiones del escritorio
        Dimension desktopSize = Escritorio.getSize();

        // Obtener las dimensiones de la ventana interna
        Dimension frameSize = ijm.getSize();

        // Calcular las coordenadas X e Y para centrar la ventana en el escritorio
        int xPos = (desktopSize.width - frameSize.width) / 2;
        int yPos = (desktopSize.height - frameSize.height) / 2;

        // Establecer la posición en el centro del escritorio
        ijm.setLocation(xPos, yPos);

        // Hacer la ventana interna visible
        ijm.setVisible(true);

        // Agregar la ventana interna al escritorio
        Escritorio.add(ijm);

        // Colocar la ventana interna al frente
        Escritorio.moveToFront(ijm);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();

        // Crear una instancia de IJAlumnos
        JFFFormularioDeInscripcion jFFF = new JFFFormularioDeInscripcion();

        // Establecer el tamaño deseado para la ventana
        int ancho = 600;
        int alto = 400;
        jFFF.setSize(ancho, alto);

        // Obtener las dimensiones del escritorio
        Dimension desktopSize = Escritorio.getSize();

        // Obtener las dimensiones de la ventana interna
        Dimension frameSize = jFFF.getSize();

        // Calcular las coordenadas X e Y para centrar la ventana en el escritorio
        int xPos = (desktopSize.width - frameSize.width) / 2;
        int yPos = (desktopSize.height - frameSize.height) / 2;

        // Establecer la posición en el centro del escritorio
        jFFF.setLocation(xPos, yPos);

        // Hacer la ventana interna visible
        jFFF.setVisible(true);

        // Agregar la ventana interna al escritorio
        Escritorio.add(jFFF);

        // Colocar la ventana interna al frente
        Escritorio.moveToFront(jFFF);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();

        // Crear una instancia de IJAlumnos
        JFFManipulacionDeNotas jFFM = new JFFManipulacionDeNotas();

        // Establecer el tamaño deseado para la ventana
        int ancho = 600;
        int alto = 400;
        jFFM.setSize(ancho, alto);

        // Obtener las dimensiones del escritorio
        Dimension desktopSize = Escritorio.getSize();

        // Obtener las dimensiones de la ventana interna
        Dimension frameSize = jFFM.getSize();

        // Calcular las coordenadas X e Y para centrar la ventana en el escritorio
        int xPos = (desktopSize.width - frameSize.width) / 2;
        int yPos = (desktopSize.height - frameSize.height) / 2;

        // Establecer la posición en el centro del escritorio
        jFFM.setLocation(xPos, yPos);

        // Hacer la ventana interna visible
        jFFM.setVisible(true);

        // Agregar la ventana interna al escritorio
        Escritorio.add(jFFM);

        // Colocar la ventana interna al frente
        Escritorio.moveToFront(jFFM);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();

        // Crear una instancia de IJAlumnos
        JFFAlumnoxmateria jFFA = new JFFAlumnoxmateria();

        // Establecer el tamaño deseado para la ventana
        int ancho = 600;
        int alto = 400;
        jFFA.setSize(ancho, alto);

        // Obtener las dimensiones del escritorio
        Dimension desktopSize = Escritorio.getSize();

        // Obtener las dimensiones de la ventana interna
        Dimension frameSize = jFFA.getSize();

        // Calcular las coordenadas X e Y para centrar la ventana en el escritorio
        int xPos = (desktopSize.width - frameSize.width) / 2;
        int yPos = (desktopSize.height - frameSize.height) / 2;

        // Establecer la posición en el centro del escritorio
        jFFA.setLocation(xPos, yPos);

        // Hacer la ventana interna visible
        jFFA.setVisible(true);

        // Agregar la ventana interna al escritorio
        Escritorio.add(jFFA);

        // Colocar la ventana interna al frente
        Escritorio.moveToFront(jFFA);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
